// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: tasks_service.proto

package tasks_protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_tasks_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_tasks_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTasksIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksIDsRequest) Reset() {
	*x = GetTasksIDsRequest{}
	mi := &file_tasks_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksIDsRequest) ProtoMessage() {}

func (x *GetTasksIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksIDsRequest.ProtoReflect.Descriptor instead.
func (*GetTasksIDsRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksIDsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTasksIDsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTasksIDsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTasksIDsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetTasksIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Results       []int32                `protobuf:"varint,2,rep,packed,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksIDsResponse) Reset() {
	*x = GetTasksIDsResponse{}
	mi := &file_tasks_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksIDsResponse) ProtoMessage() {}

func (x *GetTasksIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksIDsResponse.ProtoReflect.Descriptor instead.
func (*GetTasksIDsResponse) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksIDsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTasksIDsResponse) GetResults() []int32 {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Expertise     string                 `protobuf:"bytes,4,opt,name=expertise,proto3" json:"expertise,omitempty"`
	PatientId     int32                  `protobuf:"varint,5,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_tasks_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetExpertise() string {
	if x != nil {
		return x.Expertise
	}
	return ""
}

func (x *CreateTaskRequest) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_tasks_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_tasks_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_tasks_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{7}
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_tasks_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_tasks_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTasksByPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PatientId     int32                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksByPatientRequest) Reset() {
	*x = GetTasksByPatientRequest{}
	mi := &file_tasks_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksByPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksByPatientRequest) ProtoMessage() {}

func (x *GetTasksByPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksByPatientRequest.ProtoReflect.Descriptor instead.
func (*GetTasksByPatientRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetTasksByPatientRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTasksByPatientRequest) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

type GetTasksByPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksByPatientResponse) Reset() {
	*x = GetTasksByPatientResponse{}
	mi := &file_tasks_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksByPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksByPatientResponse) ProtoMessage() {}

func (x *GetTasksByPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksByPatientResponse.ProtoReflect.Descriptor instead.
func (*GetTasksByPatientResponse) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetTasksByPatientResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Expertise     string                 `protobuf:"bytes,5,opt,name=expertise,proto3" json:"expertise,omitempty"`
	PatientId     int32                  `protobuf:"varint,6,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tasks_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_service_proto_rawDescGZIP(), []int{12}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetExpertise() string {
	if x != nil {
		return x.Expertise
	}
	return ""
}

func (x *Task) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_tasks_service_proto protoreflect.FileDescriptor

const file_tasks_service_proto_rawDesc = "" +
	"\n" +
	"\x13tasks_service.proto\x12\x05tasks\"6\n" +
	"\x0eGetTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"2\n" +
	"\x0fGetTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.tasks.TaskR\x04task\"p\n" +
	"\x12GetTasksIDsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"E\n" +
	"\x13GetTasksIDsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x18\n" +
	"\aresults\x18\x02 \x03(\x05R\aresults\"\x9e\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\texpertise\x18\x04 \x01(\tR\texpertise\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x05 \x01(\x05R\tpatientId\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"9\n" +
	"\x11DeleteTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"J\n" +
	"\x11UpdateTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\x04task\x18\x02 \x01(\v2\v.tasks.TaskR\x04task\"$\n" +
	"\x12UpdateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"O\n" +
	"\x18GetTasksByPatientRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x05R\tpatientId\">\n" +
	"\x19GetTasksByPatientResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.tasks.TaskR\x05tasks\"\xc6\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\texpertise\x18\x05 \x01(\tR\texpertise\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x06 \x01(\x05R\tpatientId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt2\xaf\x03\n" +
	"\fTasksService\x128\n" +
	"\aGetTask\x12\x15.tasks.GetTaskRequest\x1a\x16.tasks.GetTaskResponse\x12D\n" +
	"\vGetTasksIDs\x12\x19.tasks.GetTasksIDsRequest\x1a\x1a.tasks.GetTasksIDsResponse\x12A\n" +
	"\n" +
	"CreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12A\n" +
	"\n" +
	"DeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x19.tasks.DeleteTaskResponse\x12A\n" +
	"\n" +
	"UpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x19.tasks.UpdateTaskResponse\x12V\n" +
	"\x11GetTasksByPatient\x12\x1f.tasks.GetTasksByPatientRequest\x1a .tasks.GetTasksByPatientResponseB8Z6github.com/TekClinic/Tasks-MicroService/tasks_protobufb\x06proto3"

var (
	file_tasks_service_proto_rawDescOnce sync.Once
	file_tasks_service_proto_rawDescData []byte
)

func file_tasks_service_proto_rawDescGZIP() []byte {
	file_tasks_service_proto_rawDescOnce.Do(func() {
		file_tasks_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_service_proto_rawDesc), len(file_tasks_service_proto_rawDesc)))
	})
	return file_tasks_service_proto_rawDescData
}

var file_tasks_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tasks_service_proto_goTypes = []any{
	(*GetTaskRequest)(nil),            // 0: tasks.GetTaskRequest
	(*GetTaskResponse)(nil),           // 1: tasks.GetTaskResponse
	(*GetTasksIDsRequest)(nil),        // 2: tasks.GetTasksIDsRequest
	(*GetTasksIDsResponse)(nil),       // 3: tasks.GetTasksIDsResponse
	(*CreateTaskRequest)(nil),         // 4: tasks.CreateTaskRequest
	(*CreateTaskResponse)(nil),        // 5: tasks.CreateTaskResponse
	(*DeleteTaskRequest)(nil),         // 6: tasks.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),        // 7: tasks.DeleteTaskResponse
	(*UpdateTaskRequest)(nil),         // 8: tasks.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),        // 9: tasks.UpdateTaskResponse
	(*GetTasksByPatientRequest)(nil),  // 10: tasks.GetTasksByPatientRequest
	(*GetTasksByPatientResponse)(nil), // 11: tasks.GetTasksByPatientResponse
	(*Task)(nil),                      // 12: tasks.Task
}
var file_tasks_service_proto_depIdxs = []int32{
	12, // 0: tasks.GetTaskResponse.task:type_name -> tasks.Task
	12, // 1: tasks.UpdateTaskRequest.task:type_name -> tasks.Task
	12, // 2: tasks.GetTasksByPatientResponse.tasks:type_name -> tasks.Task
	0,  // 3: tasks.TasksService.GetTask:input_type -> tasks.GetTaskRequest
	2,  // 4: tasks.TasksService.GetTasksIDs:input_type -> tasks.GetTasksIDsRequest
	4,  // 5: tasks.TasksService.CreateTask:input_type -> tasks.CreateTaskRequest
	6,  // 6: tasks.TasksService.DeleteTask:input_type -> tasks.DeleteTaskRequest
	8,  // 7: tasks.TasksService.UpdateTask:input_type -> tasks.UpdateTaskRequest
	10, // 8: tasks.TasksService.GetTasksByPatient:input_type -> tasks.GetTasksByPatientRequest
	1,  // 9: tasks.TasksService.GetTask:output_type -> tasks.GetTaskResponse
	3,  // 10: tasks.TasksService.GetTasksIDs:output_type -> tasks.GetTasksIDsResponse
	5,  // 11: tasks.TasksService.CreateTask:output_type -> tasks.CreateTaskResponse
	7,  // 12: tasks.TasksService.DeleteTask:output_type -> tasks.DeleteTaskResponse
	9,  // 13: tasks.TasksService.UpdateTask:output_type -> tasks.UpdateTaskResponse
	11, // 14: tasks.TasksService.GetTasksByPatient:output_type -> tasks.GetTasksByPatientResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tasks_service_proto_init() }
func file_tasks_service_proto_init() {
	if File_tasks_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_service_proto_rawDesc), len(file_tasks_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_service_proto_goTypes,
		DependencyIndexes: file_tasks_service_proto_depIdxs,
		MessageInfos:      file_tasks_service_proto_msgTypes,
	}.Build()
	File_tasks_service_proto = out.File
	file_tasks_service_proto_goTypes = nil
	file_tasks_service_proto_depIdxs = nil
}
